// 악기 id -> 표시 이름 (public/data/inst_*.js 에서 자동 추출)
export default {
  "violin": "바이올린",
  "viola": "비올라",
  "cello": "첼로",
  "double_bass": "더블베이스(콘트라베이스)",
  "baroque_violin": "바로크 바이올린",
  "baroque_cello": "바로크 첼로",
  "viola_damore": "비올라 다모레",
  "viola_da_gamba": "비올라 다 감바",
  "violoncello_da_spalla": "비올론첼로 다 스팔라",
  "lirone": "리로네",
  "rebec": "레벡",
  "trumpet": "트럼펫",
  "cornet": "코넷",
  "flugelhorn": "플루겔혼",
  "trombone": "트롬본",
  "sackbut": "사크부트",
  "french_horn": "프렌치호른",
  "natural_horn": "내추럴 호른",
  "natural_trumpet": "내추럴 트럼펫",
  "euphonium": "유포니엄",
  "tuba": "튜바",
  "sousaphone": "수자폰",
  "alphorn": "알프호른",
  "serpent": "세르팡",
  "didgeridoo": "디저리두",
  "marimba": "마림바",
  "vibraphone": "비브라폰",
  "xylo_glocken": "실로폰·글로켄슈필",
  "timpani": "팀파니",
  "steelpan": "스틸팬",
  "handpan": "핸드팬",
  "tongue_drum": "텅드럼",
  "handbell": "핸드벨·콰이어차임",
  "tubular_bells": "튜블러차임",
  "hardanger_fiddle": "하딩펠레",
  "nyckelharpa": "니켈하르파",
  "erhu": "얼후",
  "haegeum": "해금",
  "ajaeng": "아쟁",
  "morin_khuur": "마두금",
  "kamancheh": "카만체",
  "sarangi": "사랑기",
  "hurdy_gurdy": "허디거디",
  "gayageum": "가야금",
  "geomungo": "거문고",
  "koto": "고토",
  "shamisen": "샤미센",
  "pipa": "비파",
  "guzheng": "고쟁",
  "guqin": "구친",
  "oud": "우드",
  "saz": "사즈",
  "sitar": "시타르",
  "kora": "코라",
  "santur": "산투르",
  "hammered_dulcimer": "해머드 덜시머",
  "cimbalom": "침발롬",
  "kalimba": "칼림바",
  "classical_guitar": "클래식 기타",
  "flamenco_guitar": "플라멩코 기타",
  "acoustic_guitar": "어쿠스틱 기타",
  "electric_guitar": "일렉 기타",
  "bass_guitar": "베이스 기타",
  "ukulele": "우쿨렐레",
  "guitalele": "기타렐레",
  "twelve_string_guitar": "12현 기타",
  "resonator_guitar": "리조네이터 기타",
  "lap_steel": "랩스틸 기타",
  "pedal_steel": "페달스틸 기타",
  "banjo": "밴조",
  "mandolin": "만돌린",
  "octave_mandolin": "옥타브 만돌린",
  "mandola": "만돌라",
  "mandocello": "만도첼로",
  "mandobass": "만도베이스",
  "irish_bouzouki": "아이리시 부주키",
  "greek_bouzouki": "그리스 부주키",
  "bandolim": "반돌림",
  "concert_harp": "콘서트 하프",
  "lever_harp": "레버 하프 (켈틱 하프)",
  "lyre_harp": "라이어 하프",
  "triple_harp": "바로크 트리플 하프",
  "wire_harp": "아이리시 와이어 하프 (클라르사흐)",
  "autoharp": "오토하프",
  "mountain_dulcimer": "마운틴 덜시머",
  "balalaika": "발랄라이카",
  "charango": "샤랑고",
  "cavaquinho": "카바키뉴",
  "cittern_modern": "시턴 (모던 시턴)",
  "renaissance_lute": "르네상스 류트",
  "baroque_lute": "바로크 류트",
  "archlute": "아치류트",
  "theorbo": "테오르보",
  "baroque_guitar": "바로크 기타",
  "renaissance_guitar": "르네상스 기타",
  "vihuela": "비우엘라",
  "mandolino": "만돌리노 (바로크 만돌린)",
  "renaissance_cittern": "르네상스 시턴",
  "orpharion": "오르파리온",
  "bandora": "반도라",
  "gallichon": "갈리숑 (만도라)",
  "psaltery": "살터리 (프살테리움)",
  "piano": "피아노",
  "pipe_organ": "파이프오르간",
  "hammond_organ": "하몬드오르간",
  "harpsichord": "하프시코드",
  "clavichord": "클라비코드",
  "celesta": "첼레스타",
  "toy_piano": "토이피아노",
  "synthesizer": "신디사이저",
  "keytar": "키타",
  "melodica": "멜로디카",
  "piano_accordion": "피아노 아코디언",
  "bayan": "바얀",
  "cba_c_system": "크로매틱 버튼 아코디언",
  "diatonic_button_accordion": "다이어토닉 버튼 아코디언",
  "bandoneon": "반도네온",
  "concertina": "콘서티나",
  "diatonic_harmonica": "다이어토닉 하모니카",
  "chromatic_harmonica": "크로매틱 하모니카",
  "tremolo_harmonica": "트레몰로 하모니카",
  "saenghwang": "생황",
  "drum_set": "드럼 세트",
  "finger_drum": "핑거드럼",
  "sample_pad": "샘플패드",
  "cajon": "카혼",
  "djembe": "젬베",
  "conga": "콩가",
  "bongo": "봉고",
  "darbuka": "다르부카",
  "frame_drum": "프레임드럼",
  "pandeiro": "팬데이로",
  "tabla": "타블라",
  "bodhran": "바우런",
  "janggu": "장구",
  "tibetan_bowl": "티베탄 싱잉볼",
  "crystal_bowl": "크리스탈 싱잉볼",
  "gong": "공(Gong)",
  "koshi_chime": "코시차임·윈드차임",
  "rainstick": "레인스틱",
  "ocean_drum": "오션드럼",
  "tuning_fork": "튜닝포크(사운드테라피)",
  "launchpad": "론치패드·미디 컨트롤러",
  "ewi": "EWI·에어로폰",
  "theremin": "테레민",
  "ondes_martenot": "옹드 마르트노",
  "otamatone": "오타마톤",
  "jaw_harp": "구금(입 하프)",
  "kazoo": "카주",
  "glass_harp": "글라스 하프(물잔 연주)",
  "musical_saw": "뮤지컬 쏘(톱 연주)",
  "hand_percussion": "핸드 퍼커션 멀티",
  "tin_whistle": "틴휘슬",
  "low_whistle": "로우휘슬",
  "ocarina": "오카리나",
  "pan_flute": "팬플루트",
  "quena": "케나",
  "shakuhachi": "샤쿠하치",
  "danso": "단소",
  "sogeum": "소금",
  "daegeum": "대금",
  "piri": "피리",
  "taepyeongso": "태평소",
  "duduk": "두둑",
  "ney": "네이",
  "bansuri": "반수리",
  "dizi": "디지",
  "xiao": "샤오",
  "hulusi": "후루쓰",
  "highland_bagpipe": "하이랜드 백파이프",
  "uilleann_pipes": "일리언 파이프스",
  "galician_gaita": "갈리시안 가이타",
  "recorder": "리코더",
  "flute": "플루트",
  "piccolo": "피콜로",
  "irish_flute": "아이리시 플루트",
  "clarinet": "클라리넷",
  "oboe": "오보에",
  "english_horn": "잉글리시호른",
  "bassoon": "바순",
  "saxophone": "색소폰",
  "traverso": "트라베르소",
  "baroque_oboe": "바로크 오보에",
  "dulcian": "둘시안",
  "chalumeau": "챨루모",
  "shawm": "숌",
  "crumhorn": "크룸호른",
  "cornetto": "코르네토",
  "musette_de_cour": "뮈제트 드 쿠르",
  "yangqin": "양친 (중국 양금)",
  "zhongruan": "중롼 (롼)",
  "liuqin": "류친",
  "sanxian": "싼시엔 (삼현)",
  "konghou": "콩허우 (공후)",
  "jinghu": "징후 (경호)",
  "suona": "쑤오나",
  "bawu": "바우",
  "xun": "쉰",
  "sheng": "셩",
  "muyu": "목탁",
};
