// 악기 id -> 영어 표시 이름 (public/i18n/en_*.js 에서 자동 추출)
export default {
  "piano": "Piano",
  "pipe_organ": "Pipe organ",
  "hammond_organ": "Hammond organ",
  "harpsichord": "Harpsichord",
  "clavichord": "Clavichord",
  "celesta": "Celesta",
  "toy_piano": "Toy piano",
  "synthesizer": "Synthesizer",
  "keytar": "Keytar",
  "melodica": "Melodica",
  "piano_accordion": "Piano accordion",
  "bayan": "Bayan",
  "cba_c_system": "Chromatic button accordion",
  "diatonic_button_accordion": "Diatonic button accordion",
  "bandoneon": "Bandoneon",
  "concertina": "Concertina",
  "diatonic_harmonica": "Diatonic harmonica",
  "chromatic_harmonica": "Chromatic harmonica",
  "tremolo_harmonica": "Tremolo harmonica",
  "saenghwang": "Saenghwang",
  "violin": "Violin",
  "viola": "Viola",
  "cello": "Cello",
  "double_bass": "Double bass (contrabass)",
  "baroque_violin": "Baroque violin",
  "baroque_cello": "Baroque cello",
  "viola_damore": "Viola d'amore",
  "viola_da_gamba": "Viola da gamba",
  "violoncello_da_spalla": "Violoncello da spalla",
  "lirone": "Lirone",
  "rebec": "Rebec",
  "hardanger_fiddle": "Hardanger fiddle",
  "nyckelharpa": "Nyckelharpa",
  "erhu": "Erhu",
  "haegeum": "Haegeum",
  "ajaeng": "Ajaeng",
  "morin_khuur": "Morin khuur",
  "kamancheh": "Kamancheh",
  "sarangi": "Sarangi",
  "hurdy_gurdy": "Hurdy-gurdy",
  "gayageum": "Gayageum",
  "geomungo": "Geomungo",
  "koto": "Koto",
  "shamisen": "Shamisen",
  "pipa": "Pipa",
  "guzheng": "Guzheng",
  "guqin": "Guqin",
  "oud": "Oud",
  "saz": "Saz (bağlama)",
  "sitar": "Sitar",
  "kora": "Kora",
  "santur": "Santur",
  "hammered_dulcimer": "Hammered dulcimer",
  "cimbalom": "Cimbalom",
  "kalimba": "Kalimba",
  "classical_guitar": "Classical guitar",
  "flamenco_guitar": "Flamenco guitar",
  "acoustic_guitar": "Acoustic guitar",
  "electric_guitar": "Electric guitar",
  "bass_guitar": "Bass guitar",
  "ukulele": "Ukulele",
  "guitalele": "Guitalele",
  "twelve_string_guitar": "12-string guitar",
  "resonator_guitar": "Resonator guitar (Dobro)",
  "lap_steel": "Lap steel guitar",
  "pedal_steel": "Pedal steel guitar",
  "banjo": "Banjo",
  "mandolin": "Mandolin",
  "octave_mandolin": "Octave mandolin",
  "mandola": "Mandola",
  "mandocello": "Mandocello",
  "mandobass": "Mandobass",
  "irish_bouzouki": "Irish bouzouki",
  "greek_bouzouki": "Greek bouzouki",
  "bandolim": "Bandolim",
  "concert_harp": "Concert harp (pedal harp)",
  "lever_harp": "Lever harp (Celtic harp)",
  "lyre_harp": "Lyre harp",
  "triple_harp": "Baroque triple harp",
  "wire_harp": "Irish wire-strung harp (clarsach)",
  "autoharp": "Autoharp",
  "mountain_dulcimer": "Mountain dulcimer",
  "balalaika": "Balalaika",
  "charango": "Charango",
  "cavaquinho": "Cavaquinho",
  "cittern_modern": "Cittern (modern cittern)",
  "renaissance_lute": "Renaissance lute",
  "baroque_lute": "Baroque lute",
  "archlute": "Archlute",
  "theorbo": "Theorbo",
  "baroque_guitar": "Baroque guitar",
  "renaissance_guitar": "Renaissance guitar",
  "vihuela": "Vihuela",
  "mandolino": "Mandolino (Baroque mandolin)",
  "renaissance_cittern": "Renaissance cittern",
  "orpharion": "Orpharion",
  "bandora": "Bandora",
  "gallichon": "Gallichon (mandora)",
  "psaltery": "Psaltery",
  "recorder": "Recorder",
  "flute": "Flute",
  "piccolo": "Piccolo",
  "irish_flute": "Irish flute",
  "clarinet": "Clarinet",
  "oboe": "Oboe",
  "english_horn": "English horn (cor anglais)",
  "bassoon": "Bassoon",
  "saxophone": "Saxophone",
  "traverso": "Traverso (Baroque flute)",
  "baroque_oboe": "Baroque oboe",
  "dulcian": "Dulcian",
  "chalumeau": "Chalumeau",
  "shawm": "Shawm",
  "crumhorn": "Crumhorn",
  "cornetto": "Cornetto",
  "musette_de_cour": "Musette de cour",
  "tin_whistle": "Tin whistle",
  "low_whistle": "Low whistle",
  "ocarina": "Ocarina",
  "pan_flute": "Pan flute",
  "quena": "Quena",
  "shakuhachi": "Shakuhachi",
  "danso": "Danso",
  "sogeum": "Sogeum",
  "daegeum": "Daegeum",
  "piri": "Piri",
  "taepyeongso": "Taepyeongso",
  "duduk": "Duduk",
  "ney": "Ney",
  "bansuri": "Bansuri",
  "dizi": "Dizi",
  "xiao": "Xiao",
  "hulusi": "Hulusi",
  "highland_bagpipe": "Great Highland bagpipe",
  "uilleann_pipes": "Uilleann pipes",
  "galician_gaita": "Galician gaita",
  "trumpet": "Trumpet",
  "cornet": "Cornet",
  "flugelhorn": "Flugelhorn",
  "trombone": "Trombone",
  "sackbut": "Sackbut",
  "french_horn": "French horn",
  "natural_horn": "Natural horn",
  "natural_trumpet": "Natural trumpet",
  "euphonium": "Euphonium",
  "tuba": "Tuba",
  "sousaphone": "Sousaphone",
  "alphorn": "Alphorn",
  "serpent": "Serpent",
  "didgeridoo": "Didgeridoo",
  "marimba": "Marimba",
  "vibraphone": "Vibraphone",
  "xylo_glocken": "Xylophone & glockenspiel",
  "timpani": "Timpani",
  "steelpan": "Steelpan",
  "handpan": "Handpan",
  "tongue_drum": "Tongue drum",
  "handbell": "Handbells & choir chimes",
  "tubular_bells": "Tubular bells",
  "drum_set": "Drum set",
  "finger_drum": "Finger drumming",
  "sample_pad": "Sample pad",
  "cajon": "Cajon",
  "djembe": "Djembe",
  "conga": "Conga",
  "bongo": "Bongos",
  "darbuka": "Darbuka (doumbek)",
  "frame_drum": "Frame drum",
  "pandeiro": "Pandeiro",
  "tabla": "Tabla",
  "bodhran": "Bodhran",
  "janggu": "Janggu",
  "tibetan_bowl": "Tibetan singing bowl",
  "crystal_bowl": "Crystal singing bowl",
  "gong": "Gong",
  "koshi_chime": "Koshi chimes & wind chimes",
  "rainstick": "Rainstick",
  "ocean_drum": "Ocean drum",
  "tuning_fork": "Tuning forks (sound therapy)",
  "launchpad": "Launchpad & MIDI controller",
  "ewi": "EWI / Aerophone",
  "theremin": "Theremin",
  "ondes_martenot": "Ondes Martenot",
  "otamatone": "Otamatone",
  "jaw_harp": "Jaw harp",
  "kazoo": "Kazoo",
  "glass_harp": "Glass harp",
  "musical_saw": "Musical saw",
  "hand_percussion": "Hand percussion set",
};
